# Generated by Django 5.2.9 on 2025-12-17 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsanweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField(help_text='Automatisch generiert in 10er-Schritten, aber änderbar', unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nummer')),
                ('name', models.CharField(help_text='Name der Arbeitsanweisung', max_length=255, verbose_name='Name')),
                ('arbeitsplatz', models.CharField(choices=[('montage', 'Montage'), ('produktion', 'Produktion'), ('verpackung', 'Verpackung'), ('qualitaetskontrolle', 'Qualitätskontrolle'), ('lager', 'Lager'), ('versand', 'Versand')], max_length=50, verbose_name='Arbeitsplatz')),
                ('datei_pfad', models.CharField(blank=True, help_text='Pfad zur Datei im Filesystem', max_length=500, null=True, unique=True, verbose_name='Dateipfad')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Arbeitsanweisung',
                'verbose_name_plural': 'Arbeitsanweisungen',
                'ordering': ['nummer'],
            },
        ),
    ]
