# Generated by Django 5.2.9 on 2025-12-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsanweisungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsanweisung',
            name='kategorie',
            field=models.CharField(choices=[('alle', 'Alle'), ('prozessbeschreibung', 'Prozessbeschreibung'), ('arbeitsanweisung', 'Arbeitsanweisung'), ('betriebsanweisung', 'Betriebsanweisung')], default='arbeitsanweisung', help_text='Art der Anweisung', max_length=50, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='arbeitsanweisung',
            name='arbeitsplatz',
            field=models.CharField(choices=[('alle Abteilungen', 'Alle Abteilungen'), ('abkanten', 'Abkanten'), ('arbeitsvorbereitung', 'Arbeitsvorbereitung'), ('konstruktion', 'Konstruktion'), ('Lasern_stanzen', 'Lasern & Stanzen'), ('montage', 'Montage'), ('programmieren', 'Programmieren'), ('qualitaetssicherung', 'Qualitätssicherung'), ('schweissen', 'Schweißen'), ('versand', 'Versand'), ('zerspanen', 'Zerspanen')], max_length=100, verbose_name='Arbeitsplatz'),
        ),
    ]
