# Generated by Django 5.2.9 on 2025-12-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsanweisungen', '0002_arbeitsanweisung_kategorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbeitsanweisung',
            name='arbeitsplatz',
        ),
        migrations.AddField(
            model_name='arbeitsanweisung',
            name='arbeitsplaetze',
            field=models.JSONField(default=list, help_text='Wählen Sie einen oder mehrere Arbeitsplätze', verbose_name='Arbeitsplätze'),
        ),
    ]
