# Generated by Django 5.2.9 on 2025-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsanweisungen', '0003_remove_arbeitsanweisung_arbeitsplatz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsanweisung',
            name='kategorie',
            field=models.CharField(choices=[('prozessbeschreibung', 'Prozessbeschreibung'), ('arbeitsanweisung', 'Arbeitsanweisung'), ('betriebsanweisung', 'Betriebsanweisung')], default='arbeitsanweisung', help_text='Art der Anweisung', max_length=50, verbose_name='Kategorie'),
        ),
    ]
