# Generated by Django 5.2.9 on 2026-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsanweisungen', '0004_alter_arbeitsanweisung_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitsanweisung',
            name='revision',
            field=models.IntegerField(default=1, help_text='Revisionsstand', verbose_name='Revision'),
        ),
        migrations.AlterField(
            model_name='arbeitsanweisung',
            name='kategorie',
            field=models.CharField(choices=[('prozessbeschreibung', 'Prozessbeschreibung'), ('arbeitsanweisung', 'Arbeitsanweisung'), ('betriebsanweisung', 'Betriebsanweisung'), ('stellenbeschreibung', 'Stellenbeschreibung'), ('formblaetter', 'Formblätter')], default='arbeitsanweisung', help_text='Art der Anweisung', max_length=50, verbose_name='Kategorie'),
        ),
    ]
