# Generated by Django 5.2.9 on 2026-01-23 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbeitsanweisungen', '0005_arbeitsanweisung_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbeitsanweisung',
            name='revision',
            field=models.IntegerField(default=1, help_text='Revisionsstand', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Revision'),
        ),
    ]
